### ISSUE TITLE
kube-vxlan-controller not running on kubernetes 1.16.1

### ISSUE THREAD

**Issue by jvilcans** [openvnf/kube-vxlan-controller#1]
kube-vxlan-controller not running correctly on kubernetes 1.16.1 

1) apiVersion must be changed to apps/v1
2) selector and label must be added
3) when running the deployment it runs for couple of seconds, crashes and restarts.

```
kube-system   kube-vxlan-controller-f4f4bb656-4kllq      0/1     CrashLoopBackOff   26         119m

ubuntu@worker-1a:~$ kubectl -nkube-system describe pod kube-vxlan-controller-f4f4bb656-4kllq
Name:         kube-vxlan-controller-f4f4bb656-4kllq
Namespace:    kube-system
Priority:     0
Node:         worker-1a/10.123.76.16
Start Time:   Thu, 09 Jan 2020 09:56:38 +0000
Labels:       pod-template-hash=f4f4bb656
              run=kube-vxlan-controller
Annotations:  cni.projectcalico.org/podIP: 10.10.100.74/32
Status:       Running
IP:           10.10.100.74
IPs:
  IP:           10.10.100.74
Controlled By:  ReplicaSet/kube-vxlan-controller-f4f4bb656
Containers:
  kube-vxlan-controller:
    Container ID:  docker://f1e35789f19d64c5013bd2dc1a827696b41260f018b9c06f6d674c007ae3c20f
    Image:         openvnf/kube-vxlan-controller:latest
    Image ID:      docker-pullable://openvnf/kube-vxlan-controller@sha256:b989aa8106cee3a24eaf0058d7e8e69d78a32602cafed2835b0e0488aa4d6307
    Port:          <none>
    Host Port:     <none>
    Args:
      run
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 09 Jan 2020 11:52:10 +0000
      Finished:     Thu, 09 Jan 2020 11:52:26 +0000
    Ready:          False
    Restart Count:  26
    Environment:    <none>
    Mounts:
      /etc/kube-vxlan-controller from kube-vxlan-controller-config (rw)
      /usr/share/kube-vxlan-controller from kube-vxlan-controller-db (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-vxlan-controller-token-wdrlp (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-vxlan-controller-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-vxlan-controller-config
    Optional:  false
  kube-vxlan-controller-db:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-vxlan-controller-token-wdrlp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-vxlan-controller-token-wdrlp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                   From                Message
  ----     ------   ----                  ----                -------
  Normal   Pulling  10m (x26 over 120m)   kubelet, worker-1a  Pulling image "openvnf/kube-vxlan-controller:latest"
  Warning  BackOff  37s (x515 over 120m)  kubelet, worker-1a  Back-off restarting failed container
```

Full manifest:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vxlan-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-vxlan-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-vxlan-controller
    namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vxlan-controller
  namespace: kube-system
data:
  vxeth0: id=100 up
  vxeth1: id=101 up
  vxeth2: id=102 up
  vxeth3: id=103 up
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-vxlan-controller-config
  namespace: kube-system
data:
  config: |
    [{'kube-vxlan-controller', [
        {db_file, "/usr/share/kube-vxlan-controller/db"},
        {selector, "vxlan.openvnf.org"},
        {annotation, "vxlan.openvnf.org/networks"}
    ]}].
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kube-vxlan-controller
  name: kube-vxlan-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      run: kube-vxlan-controller
  template:
    metadata:
      labels:
        run: kube-vxlan-controller
    spec:
      containers:
      - name: kube-vxlan-controller
        image: openvnf/kube-vxlan-controller:0.10.2
        args:
        - run
        volumeMounts:
        - name: kube-vxlan-controller-config
          mountPath: /etc/kube-vxlan-controller
        - name: kube-vxlan-controller-db
          mountPath: /usr/share/kube-vxlan-controller
      volumes:
      - name: kube-vxlan-controller-config
        configMap:
          name: kube-vxlan-controller-config
      - name: kube-vxlan-controller-db
        emptyDir: {}
      serviceAccount: kube-vxlan-controller
      serviceAccountName: kube-vxlan-controller
```

```
ubuntu@worker-1a:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
