### ISSUE TITLE
Scaling deployment results in duplicated IP adresses in replicas

### ISSUE THREAD

**Issue by lmckoko-ericsson** [openvnf/kube-vxlan-controller#8]
Hi,

I have tried to scale a deployment with replicas=2, unfortunately both replicas were assigned the same IP address, as set in the annotation;

```
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      run: a
      vxlan.openvnf.org: "true"
    name: a
  spec:
    progressDeadlineSeconds: 2147483647
    replicas: 2
    revisionHistoryLimit: 2147483647
    selector:
      matchLabels:
        run: a
        vxlan.openvnf.org: "true"
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        annotations:
          vxlan.openvnf.org/networks: |
            vxeth1
              ip=**192.168.11.2/24**
              route=192.168.12.0/29:192.168.11.1
        creationTimestamp: null
        labels:
          run: a
          vxlan.openvnf.org: "true"

```

After both replicas have deployed, I see the same IP address in both replicas:

```
k get pods
NAME                  READY   STATUS    RESTARTS   AGE
**a-58b8f56785-56bgq**    2/2     Running   0          15m
**a-58b8f56785-8rrmx**    2/2     Running   0          15m
b-69f6578949-xrhw2    2/2     Running   0          15m
gw-85fcb84c48-fmh2w   2/2     Running   0          15m

k exec -it **a-58b8f56785-56bgq** -- ifconfig vxeth1
Defaulted container "a" out of: a, vxlan-controller-agent, vxlan-controller-agent-init (init)
vxeth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet **192.168.11.2**  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::d864:4bff:fe72:2db7  prefixlen 64  scopeid 0x20<link>
        ether da:64:4b:72:2d:b7  txqueuelen 1000  (Ethernet)
        RX packets 13  bytes 728 (728.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 784 (784.0 B)
        TX errors 0  dropped 6 overruns 0  carrier 0  collisions 0

k exec -it **a-58b8f56785-8rrmx** -- ifconfig vxeth1
Defaulted container "a" out of: a, vxlan-controller-agent, vxlan-controller-agent-init (init)
vxeth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet **192.168.11.2**  netmask 255.255.255.0  broadcast 0.0.0.0
        inet6 fe80::a021:fcff:feb8:57d1  prefixlen 64  scopeid 0x20<link>
        ether a2:21:fc:b8:57:d1  txqueuelen 1000  (Ethernet)
        RX packets 14  bytes 784 (784.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 784 (784.0 B)
        TX errors 0  dropped 6 overruns 0  carrier 0  collisions 0

```

Is there a way to specify a subnet but not a hard-coded IP address in the annotation?

Thanks!
